on:
  push:
  workflow_dispatch:

env:
  RUN_TESTS: 'true'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.14
      - name: init
        run: |
          echo 'step init'
          pwd && ls
          env
          echo ${{ secrets.DOCKERHUB_TOKEN }}
          echo ${{ env.RUN_TESTS }}
          java -version
          mvn -v
          docker version
      - name: Build maven package
        run: mvn package -DskipTests

      - if: env.RUN_TESTS == 'true'
        name: Run maven tests
        run: mvn test -P run-integration-tests

      - name: Build docker image
        run: docker build -t lion78at/calculator --no-cache .

      - name: Push docker image
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u lion78at --password-stdin
          docker push lion78at/calculator
        
