on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: init
        run: |
          echo 'step init'
          pwd && ls
          env
          echo ${{ secrets.DOCKERHUB_TOKEN }}
          echo ${{ env.RUN_TESTS }}
          java -version
          mvn -v
          docker version
      - name: build
        run: echo 'step build'

      - name: test
        run: echo 'step test'

      - name: release
        run: echo 'step release'

      - name: deploy
        run: echo 'step deploy'
        
